### ISSUE TITLE
on Linux CPU utilization is a bit high

### ISSUE THREAD

**Issue by yuizho** [yuizho/pomors#8]
- on Linux, CPU utilization is a bit high (around 5 ~ 10 %)
  - pobably due to audio play back with rodio
https://github.com/RustAudio/rodio/issues/299

**Comment by yuizho** [comment]
probably due to this issue with radio.
https://github.com/RustAudio/rodio/issues/299

**Comment by yuizho** [comment]
This issue has been fixed as I have updated rodio 0.11.0 to 0.12.0.

**Comment by ModProg** [comment]
I think this somewhat resurfaced, after using it for a while I got this: 
![grafik](https://user-images.githubusercontent.com/11978847/138610409-c5c4694a-cd37-43fe-adaf-1990acc46f0c.png)
